### ISSUE TITLE
Prevent displaying the deleted/removed files in public profile

### ISSUE THREAD

**Issue by kritisingh1** [OpenHumans/open-humans#763] opened 2018-04-13 09:18 UTC
Steps to reproduce : 

1. Upload a file on one of the self created projects on the Open Humans website.
2. Remove/Delete the file.
3. Go to MyAccount -> Public Profile.
4. The list displayed contains files which were uploaded some time in the past and then removed. On clicking the Download option, the download occurs with a failed status and Nofile info.

I think the current feature maybe helpful in case the user wants to keep track of the files he/she uploaded in the past. However we should remove at least the Download option corresponding to the same IMO. We can remove the option as a whole as well which could be more appropriate.

@gedankenstuecke @madprime please let me know your views on this. :slightly_smiling_face: 
## General Checkups
- [x] Have you checked that there isn't already an existing issue that describes what you report below?
- [x] Have you checked that there isn't already an open pull requests for this issue/update/change?

## Description

Relevant screenshot : 
![screenshot from 2018-04-13 14-38-16](https://user-images.githubusercontent.com/22004158/38727295-3f535bf0-3f2a-11e8-9b71-3ca4621a1c67.png)

**Comment by kritisingh1** [comment] 2018-04-13 16:37
Yeah I used the open humans API for upload and delete operations through command line.

**Comment by madprime** [comment] 2018-04-14 14:01
I've tried testing this locally and I'm having trouble reproducing. I wonder if what's happened here is a cached page?

@kritisingh1 if you go back now, is the same issue present? or has it disappeared?

If it seems to be a cached page, one solution would be to add `NeverCacheMixin` from `common.mixins` to `MemberDetailView` and `MemberDataView` in `open_humans.member_views`.

**Comment by madprime** [comment] 2018-04-14 16:57
Ah, interesting! And thank you for the quick response. :) Okay, two things...

(1) The API is accepting mock files that aren't actual files? As you say, that sounds like something we might want to handle better. Can you describe steps to reproduce this behavior?

(2) "Deleting all files matching a filename" does match the documentation for our API behavior. I don't see this as a problem. If someone wants to be more specific, they can instead delete by file ID. https://www.openhumans.org/direct-sharing/oauth2-data-upload/#deleting-files

**Comment by kritisingh1** [comment] 2018-04-17 19:04
@madprime Sorry for the delayed response.

1. The API does not mock the false files once the cassette is recorded. This happened when the cassettes was recorded. So this is not a problem on the user end. It could be left as it is then in my opinion. What should be the ideal behavior according to you?

2. I agree that the user can delete the files with specific ID but I think it would be great if we introduce a prompt whether he is sure to delete all the files with the same name, just to be double sure. After he enters a `yes` we could proceed else terminate the process. Need you opinion on the same. :)

**Comment by madprime** [comment] 2018-09-13 20:59
Closing this as a rare development issue related to cassettes.

**Closed by madprime** 2018-09-13 20:59 UTC
